name = "sundae/fee-manager"
version = "0.0.0"
compiler = "v1.1.1"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'sundae/fee-manager'"

[repository]
user = "sundae"
project = "fee-manager"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.0.0"
source = "github"

[[dependencies]]
name = "SundaeSwap-finance/aicone"
version = "42b248e14879b5559d875abff5f0bcc6ff4c83b6"
source = "github"

[config]
